parameters:
#    saucis_sound_community.example.class: SaucisSound\Bundle\CommunityBundle\Example

services:
#    saucis_sound_community.example:
#        class: %saucis_sound_community.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
