parameters:
#    saucis_sound_core.example.class: SaucisSound\Bundle\CoreBundle\Example

services:
#    saucis_sound_core.example:
#        class: %saucis_sound_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
