fos_rest:
    param_fetcher_listener: force
    allowed_methods_listener: true
    routing_loader:
        default_format: json
        include_format: false
    serializer:
        serialize_null: true
    view:
        formats:
            json: true
        view_response_listener: force
        serialize_null: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }